# -*- coding: utf-8 -*-
"""Previsão com CatBoost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-KKFa_C2EpyraBgLe6vlDLysUbLdIj8
"""

"""
# @title CatBoost Financial Time Series Predictor
Environment: Google Colab (CPU)
Description: Production-ready pipeline for 1-10 day log-return predictions.
"""

# Instalação silenciosa de dependências
!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz -q && tar -xzf ta-lib-0.4.0-src.tar.gz && cd ta-lib/ && ./configure --prefix=/usr > /dev/null 2>&1 && make > /dev/null 2>&1 && make install > /dev/null 2>&1 && cd .. && pip install TA-Lib catboost optuna shap -q

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numba
import talib
import yfinance as yf
import optuna
import shap
from catboost import CatBoostRegressor, Pool
from IPython.display import display, HTML

# Supressão total de alertas estéticos/depreciação
warnings.filterwarnings("ignore")

# ==========================================
# SESSION 0: CONFIGURATION
# ==========================================
CONFIG = {
    "TICKERS": [
        'A', 'AAL', 'AALR3.SA', 'AAP', 'AAPL', 'AAZQ11.SA', 'ABBV', 'ABCB4.SA', 'ABCP11.SA', 'ABEV', 'ABNB', 'ABT', 'ACN', 'ACWI11.SA',
        'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AERI3.SA', 'AES', 'AFHI11.SA', 'AFL', 'AGXY3.SA', 'AIEC11.SA', 'AIG',
        'AIV', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALC', 'ALGN', 'ALK', 'ALL', 'ALLD3.SA', 'ALLE', 'ALNY', 'ALPA3.SA', 'ALPA4.SA', 'ALPK3.SA',
        'ALUG11.SA', 'ALUP11.SA', 'ALUP3.SA', 'ALUP4.SA', 'ALZR11.SA', 'AMAR3.SA', 'AMAT', 'AMBP3.SA', 'AMC', 'AMCR', 'AMD', 'AME', 'AMER3.SA',
        'AMGN', 'AMP', 'AMT', 'AMZN', 'ANET', 'ANIM3.SA', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APTO11.SA', 'APTV', 'ARE', 'ARES', 'ARGX',
        'ARML3.SA', 'ARRI11.SA', 'ARW', 'ARXD11.SA', 'ASAI3.SA', 'ASML', 'ASND', 'ATHM', 'ATO', 'AUGO', 'AURE3.SA', 'AVB', 'AVGO', 'AVY',
        'AWI', 'AWK', 'AXON', 'AXP', 'AZEV3.SA', 'AZEV4.SA', 'AZN', 'AZO', 'AZTA', 'B3SA3.SA', 'BA', 'BABA', 'BAC', 'BAH', 'BAK', 'BALL',
        'BALM4.SA', 'BAP', 'BAX', 'BAZA3.SA', 'BBAS3.SA', 'BBD', 'BBDO', 'BBFO11.SA', 'BBGO11.SA', 'BBOI11.SA', 'BBOV11.SA', 'BBRC11.SA',
        'BBSE3.SA', 'BBWI', 'BBY', 'BCHI39.SA', 'BCIA11.SA', 'BCRI11.SA', 'BCS', 'BDIF11.SA', 'BDIV11.SA', 'BDOM11.SA', 'BDX', 'BEEF3.SA',
        'BEEM39.SA', 'BEES3.SA', 'BEES4.SA', 'BEN', 'BFH', 'BFXI39.SA', 'BIAU39.SA', 'BIDU', 'BIIB', 'BILI', 'BILL', 'BIME11.SA', 'BIOM3.SA',
        'BITH11.SA', 'BITI11.SA', 'BIVB39.SA', 'BIVE39.SA', 'BK', 'BKNG', 'BKR', 'BL', 'BLAU3.SA', 'BLK', 'BLMG11.SA', 'BMBL', 'BMGB4.SA',
        'BMLC11.SA', 'BMOB3.SA', 'BMRN', 'BMY', 'BNDX11.SA', 'BNFS11.SA', 'BNTX', 'BODB11.SA', 'BOVA11.SA', 'BOVS11.SA', 'BOVV11.SA', 'BOVX11.SA',
        'BP', 'BPAC11.SA', 'BPML11.SA', 'BR', 'BRAP3.SA', 'BRAP4.SA', 'BRAX11.SA', 'BRBI', 'BRCO11.SA', 'BRCR11.SA', 'BRKM3.SA', 'BROF11.SA',
        'BRSR3.SA', 'BRSR6.SA', 'BSAC', 'BSBR', 'BSIL39.SA', 'BSX', 'BTAG11.SA', 'BTAL11.SA', 'BTCI11.SA', 'BTI', 'BTLG11.SA', 'BTRA11.SA',
        'BUD', 'BURA39.SA', 'BWA', 'BXP', 'BYND', 'C', 'CABO', 'CACR11.SA', 'CAG', 'CAH', 'CAMB3.SA', 'CAML3.SA', 'CARE11.SA', 'CARR', 'CASH3.SA',
        'CAT', 'CB', 'CBAV3.SA', 'CBOP11.SA', 'CBRE', 'CCI', 'CCL', 'CCME11.SA', 'CDII11.SA', 'CDNS', 'CDW', 'CE', 'CEAB3.SA', 'CEBR6.SA',
        'CEOC11.SA', 'CF', 'CFG', 'CGNX', 'CGRA3.SA', 'CGRA4.SA', 'CHD', 'CHDN', 'CHIP11.SA', 'CHKP', 'CHPT', 'CHRW', 'CHT', 'CHTR', 'CI',
        'CIG', 'CINF', 'CL', 'CLOV', 'CLSC4.SA', 'CLX', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMIG3.SA', 'CMIN3.SA', 'CMS', 'CNC', 'CNI', 'CNP',
        'COCE5.SA', 'COF', 'COGN3.SA', 'COIN', 'COLM', 'COO', 'COP', 'CORN11.SA', 'COST', 'COTY', 'COUR', 'CPB', 'CPFE3.SA', 'CPRT', 'CPSH11.SA',
        'CPT', 'CPTI11.SA', 'CPTR11.SA', 'CPTS11.SA', 'CRAA11.SA', 'CRI', 'CRM', 'CRNC', 'CRPG5.SA', 'CRPT11.SA', 'CRSP', 'CRWD', 'CSAN', 'CSCO',
        'CSED3.SA', 'CSGP', 'CSMG3.SA', 'CSUD3.SA', 'CSX', 'CTAS', 'CTRA', 'CTSH', 'CTVA', 'CURY3.SA', 'CUZ', 'CVS', 'CVX', 'CX', 'CXCI11.SA',
        'CXCO11.SA', 'CXSE3.SA', 'CYCR11.SA', 'CYRE3.SA', 'CZR', 'D', 'DAL', 'DASA3.SA', 'DASH', 'DB', 'DCRA11.SA', 'DD', 'DDOG', 'DE', 'DEFI11.SA',
        'DELL', 'DEO', 'DESK3.SA', 'DEVA11.SA', 'DEXP3.SA', 'DG', 'DGX', 'DHI', 'DHR', 'DINO', 'DIRR3.SA', 'DIS', 'DIVO11.SA', 'DKNG', 'DKS', 'DLR',
        'DLTR', 'DMVF3.SA', 'DNLI', 'DOC', 'DOCS', 'DOCU', 'DOHL4.SA', 'DOLA11.SA', 'DOTZ3.SA', 'DOV', 'DOW', 'DOX', 'DPZ', 'DRI', 'DTE', 'DUK',
        'DVA', 'DVFF11.SA', 'DVN', 'DXC', 'DXCM', 'DXCO3.SA', 'EA', 'EALT4.SA', 'EBAY', 'EC', 'ECL', 'ED', 'EDU', 'EEFT', 'EFX', 'EGAF11.SA',
        'EGIE3.SA', 'EIX', 'EL', 'ELAS11.SA', 'ELPC', 'ELS', 'ELV', 'EMAE4.SA', 'EMN', 'EMR', 'ENDD11.SA', 'ENEV3.SA', 'ENGI11.SA', 'ENGI3.SA',
        'ENGI4.SA', 'ENJU3.SA', 'ENOV', 'ENPH', 'ENTG', 'EOG', 'EPAM', 'EPD', 'EQIR11.SA', 'EQIX', 'EQNR', 'EQPA3.SA', 'EQR', 'ERIC', 'ES',
        'ESPA3.SA', 'ESS', 'ETER3.SA', 'ETN', 'ETR', 'ETSY', 'EUCA4.SA', 'EVEN3.SA', 'EVRG', 'EW', 'EXC', 'EXEL', 'EXPD', 'EXPE', 'EXR', 'F',
        'FAED11.SA', 'FANG', 'FAST', 'FATN11.SA', 'FCFL11.SA', 'FCX', 'FDX', 'FE', 'FESA4.SA', 'FFIV', 'FGAA11.SA', 'FHER3.SA', 'FICO', 'FIGS11.SA',
        'FIIB11.SA', 'FIND11.SA', 'FIQE3.SA', 'FITB', 'FIVN11.SA', 'FIXX11.SA', 'FLCR11.SA', 'FLMA11.SA', 'FLRP11.SA', 'FLRY3.SA', 'FLS', 'FMC',
        'FNF', 'FNOR11.SA', 'FNV', 'FOMO11.SA', 'FOXA', 'FR', 'FRAS3.SA', 'FRT', 'FSLR', 'FSLY', 'FTI', 'FTNT', 'FTV', 'G2DI33.SA', 'GAME11.SA',
        'GAP', 'GCRI11.SA', 'GD', 'GDDY', 'GDS', 'GE', 'GENB11.SA', 'GEPA4.SA', 'GFI', 'GFSA3.SA', 'GGB', 'GGBR3.SA', 'GGPS3.SA', 'GGRC11.SA',
        'GILD', 'GIS', 'GL', 'GLOG11.SA', 'GLPG', 'GLW', 'GM', 'GMAT3.SA', 'GMED', 'GNTX', 'GOAU3.SA', 'GOAU4.SA', 'GOLD11.SA', 'GOOG', 'GOOGL',
        'GPC', 'GPN', 'GPRK', 'GPRO', 'GRMN', 'GRND3.SA', 'GRWA11.SA', 'GS', 'GSFI11.SA', 'GSK',  'GWRE', 'GWW', 'GZIT11.SA', 'HABT11.SA',
        'HAGA4.SA', 'HAL', 'HAPV3.SA', 'HAS', 'HASH11.SA', 'HBAN', 'HBOR3.SA', 'HBRE3.SA', 'HBSA3.SA', 'HCA', 'HCHG11.SA', 'HCRI11.SA', 'HCTR11.SA',
        'HD', 'HDB', 'HEI', 'HFOF11.SA', 'HGBS11.SA', 'HGCR11.SA', 'HGIC11.SA', 'HGLG11.SA', 'HGPO11.SA', 'HGRE11.SA', 'HGRU11.SA', 'HIG',
        'HII', 'HLOG11.SA', 'HLT', 'HMC', 'HOG', 'HOLX', 'HON', 'HPE', 'HPQ', 'HRB', 'HRL', 'HSAF11.SA', 'HSBC', 'HST', 'HSY',
        'HTEK11.SA', 'HTMX11.SA', 'HUBS', 'HUM', 'HWM', 'HYPE3.SA', 'IAAG11.SA', 'IAGR11.SA', 'IBCR11.SA', 'IBM', 'ICE', 'IDXX',
        'IEX', 'IFCM3.SA', 'IFF', 'IFRA11.SA', 'IGTI11.SA', 'IHG', 'ILMN', 'INCY', 'INEP3.SA', 'INFY', 'INGR', 'INTB3.SA', 'INTC', 'INTR', 'INTU',
        'INVH', 'IP', 'IPGP', 'IQ', 'IQV', 'IR', 'IRBR3.SA', 'IRIM11.SA', 'IRM', 'ISRG', 'IT', 'ITIP11.SA', 'ITIT11.SA', 'ITSA3.SA', 'ITSA4.SA',
        'ITUB', 'ITUB3.SA', 'ITW', 'IVVB11.SA', 'IVZ', 'IX', 'J', 'JALL3.SA', 'JAZZ', 'JBHT', 'JBL', 'JBS', 'JCI', 'JD', 'JEF', 'JFEN3.SA',
        'JGPX11.SA', 'JHSF3.SA', 'JKHY', 'JNJ', 'JOGO11.SA', 'JPM', 'JPPA11.SA', 'JSAF11.SA', 'JSLG3.SA', 'JSRE11.SA', 'JURO11.SA', 'KC',
        'KCRE11.SA', 'KEPL3.SA', 'KEY', 'KEYS', 'KFOF11.SA', 'KHC', 'KIM', 'KISU11.SA', 'KIVO11.SA', 'KLAC', 'KLBN11.SA', 'KLBN3.SA', 'KLBN4.SA',
        'KMB', 'KMI', 'KMPR', 'KMX', 'KNCA11.SA', 'KNCR11.SA', 'KNHF11.SA', 'KNHY11.SA', 'KNIP11.SA', 'KNRE11.SA', 'KNRI11.SA', 'KNSC11.SA',
        'KO', 'KORE11.SA', 'KR', 'KRC', 'KSS', 'L', 'LAND3.SA', 'LAVV3.SA', 'LDOS', 'LEG', 'LEN', 'LEVE3.SA', 'LH', 'LHX', 'LIFE11.SA', 'LIGT3.SA',
        'LIVN', 'LJQQ3.SA', 'LLY', 'LMT', 'LNC', 'LND', 'LOGG3.SA', 'LOW', 'LRCX', 'LSAG11.SA', 'LSCC', 'LULU', 'LUMN', 'LUPA3.SA', 'LUV',
        'LVBI11.SA', 'LVS', 'LW', 'LWSA3.SA', 'LYB', 'LYG', 'LYV', 'M', 'MA', 'MAA', 'MANA11.SA', 'MAR', 'MAS', 'MASI', 'MATB11.SA', 'MATD3.SA',
        'MAXR11.SA', 'MBRF3.SA', 'MCCI11.SA', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDB', 'MDIA3.SA', 'MDLZ', 'MDNE3.SA', 'MDT', 'MELI', 'MELK3.SA',
        'MET', 'META', 'META11.SA', 'MFII11.SA', 'MGHT11.SA', 'MGLU3.SA', 'MGM', 'MHK', 'MILS3.SA', 'MKC', 'MKL', 'MKTX', 'MLAS3.SA', 'MMM',
        'MNPR3.SA', 'MNST', 'MO', 'MOS', 'MP', 'MPC', 'MRK', 'MRNA', 'MRVE3.SA', 'MRVL', 'MS', 'MSCI', 'MSFT', 'MSI', 'MSTR', 'MT', 'MTB', 'MTCH',
        'MTD', 'MTRE3.SA', 'MU', 'MUFG', 'MULT3.SA', 'MXRF11.SA', 'MYPK3.SA', 'NASD11.SA', 'NAVT11.SA', 'NBIX', 'NCLH', 'NCRI11.SA', 'NDAQ', 'NEE',
        'NEM', 'NEOE3.SA', 'NET', 'NEWL11.SA', 'NEWU11.SA', 'NFLX', 'NGG', 'NI', 'NICE', 'NKE', 'NLY', 'NMR', 'NOC', 'NOK', 'NOW', 'NRG', 'NSC',
        'NSLU11.SA', 'NTAP', 'NTES', 'NTRS', 'NU', 'NUE', 'NUTR3.SA', 'NVDA', 'NVO', 'NVR', 'NVS', 'NWG', 'NWL', 'NWS', 'NWSA', 'NXPI', 'O', 'ODFL',
        'ODPV3.SA', 'OGIN11.SA', 'OIAG11.SA', 'OKE', 'OKTA', 'OMC', 'ON', 'ONCO3.SA', 'OPCT3.SA', 'ORCL', 'ORLY', 'ORVR3.SA', 'OTIS', 'OXY', 'PAGS',
        'PANW', 'PATH', 'PATL11.SA', 'PAYC', 'PAYX', 'PBR', 'PCAR', 'PCAR3.SA', 'PCOR', 'PDD', 'PDGR3.SA', 'PDTC3.SA', 'PEG', 'PEP', 'PETR4.SA',
        'PFE', 'PFG', 'PFIN11.SA', 'PFRM3.SA', 'PGMN3.SA', 'PGR', 'PH', 'PHM', 'PIBB11.SA', 'PINE4.SA', 'PINS', 'PKG', 'PKX', 'PLD', 'PLNT',
        'PLPL3.SA', 'PLTR', 'PM', 'PNC', 'PNR', 'PNVL3.SA', 'PNW', 'PODD', 'POMO3.SA', 'POMO4.SA', 'PORD11.SA', 'POSI3.SA', 'PPG', 'PPL',
        'PPLA11.SA', 'PRIO3.SA', 'PRNR3.SA', 'PRU', 'PSA', 'PSSA3.SA', 'PSX', 'PTBL3.SA', 'PTNT4.SA', 'PUK', 'PVBI11.SA', 'PVH', 'PWR', 'PYPL',
        'QBTC11.SA', 'QCOM', 'QDFI11.SA', 'QRVO', 'QS', 'QSOL11.SA', 'QUAL3.SA', 'RADL3.SA', 'RAIL3.SA', 'RAIZ4.SA', 'RANI3.SA', 'RAPT3.SA',
        'RAPT4.SA', 'RBHG11.SA', 'RBHY11.SA', 'RBIR11.SA', 'RBLX', 'RBRD11.SA', 'RBRL11.SA', 'RBRP11.SA', 'RBRR11.SA', 'RBRX11.SA', 'RBRY11.SA',
        'RBVA11.SA', 'RCL', 'RCRB11.SA', 'RCSL3.SA', 'RCSL4.SA', 'RDOR3.SA', 'RDY', 'RECR11.SA', 'RECT11.SA', 'RECV3.SA', 'REDE3.SA', 'REG',
        'REGN', 'RELG11.SA', 'RELX', 'RENT3.SA', 'RF', 'RH', 'RHI', 'RIG', 'RINV11.SA', 'RIO', 'RJF', 'RL', 'RMD', 'RNEW3.SA', 'RNEW4.SA', 'ROK',
        'ROKU', 'ROL', 'ROMI3.SA', 'ROP', 'ROST', 'RPRI11.SA', 'RSG', 'RSUL4.SA', 'RTX', 'RURA11.SA', 'RYAAY', 'RZAG11.SA', 'RZAK11.SA', 'RZTR11.SA',
        'SAN', 'SANB3.SA', 'SANB4.SA', 'SAP', 'SAPR11.SA', 'SAPR3.SA', 'SAPR4.SA', 'SBFG3.SA', 'SBS', 'SBUX', 'SCAR3.SA', 'SCHW', 'SCPF11.SA', 'SE',
        'SEDG', 'SEE', 'SEER3.SA', 'SEQL3.SA', 'SEQR11.SA', 'SGML', 'SHOP', 'SHOW3.SA', 'SHPH11.SA', 'SHUL4.SA', 'SHW', 'SID', 'SIMH3.SA', 'SIRI',
        'SJM', 'SKM', 'SLB', 'SLCE3.SA', 'SMAC11.SA', 'SMAL11.SA', 'SMFG', 'SMFT3.SA', 'SMTO3.SA', 'SNA', 'SNAG11.SA', 'SNAP', 'SNCI11.SA', 'SNFF11.SA',
        'SNID11.SA', 'SNN', 'SNOW', 'SNPS', 'SO', 'SOJA3.SA', 'SOLH11.SA', 'SONY', 'SPG', 'SPGI', 'SPOT', 'SPTW11.SA', 'SPXI11.SA',
        'SPXS11.SA', 'SRE', 'SRPT', 'STE', 'STM', 'STNE', 'STT', 'STZ', 'SUZ', 'SVAL11.SA', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYNE3.SA', 'SYY', 'T',
        'TAEE11.SA', 'TAEE3.SA', 'TAEE4.SA', 'TAL', 'TAP', 'TASA3.SA', 'TASA4.SA', 'TCSA3.SA', 'TDG', 'TDOC', 'TECH', 'TECK11.SA', 'TECN3.SA', 'TEL',
        'TEND3.SA', 'TEPP11.SA', 'TFC', 'TFCO4.SA', 'TFX', 'TGAR11.SA', 'TGMA3.SA', 'TGT', 'THG', 'TIMB', 'TJX', 'TM', 'TMO', 'TMUS', 'TORD11.SA',
        'TOTS3.SA', 'TPIS3.SA', 'TPR', 'TRAD3.SA', 'TRBL11.SA', 'TRIG11.SA', 'TRIP', 'TRIS3.SA', 'TROW', 'TRV', 'TRXF11.SA', 'TS', 'TSCO', 'TSLA',
        'TSM', 'TSN', 'TT', 'TTD', 'TTEN3.SA', 'TTWO', 'TUPY3.SA', 'TWLO', 'TX', 'TXN', 'TXT', 'U', 'UAA', 'UAL', 'UBER', 'UBS', 'UCAS3.SA', 'UDR',
        'UGP', 'UHS', 'UL', 'ULTA', 'UNH', 'UNIP3.SA', 'UNIP6.SA', 'UNM', 'UNP', 'UPS', 'UPST', 'UPWK', 'URI', 'URPR11.SA', 'USAL11.SA', 'USB',
        'USDB11.SA', 'USIM3.SA', 'USIM5.SA', 'USTK11.SA', 'UTEC11.SA', 'V', 'VALE', 'VAMO3.SA', 'VBBR3.SA', 'VCJR11.SA', 'VCRA11.SA', 'VCRI11.SA',
        'VCRR11.SA', 'VEEV', 'VFC', 'VGHF11.SA', 'VGIA11.SA', 'VGIP11.SA', 'VGIR11.SA', 'VGRI11.SA', 'VILG11.SA', 'VINO11.SA', 'VIPS', 'VISC11.SA',
        'VITT3.SA', 'VIUR11.SA', 'VIV', 'VIVA3.SA', 'VIVR3.SA', 'VLID3.SA', 'VLO', 'VLY', 'VMC', 'VNO', 'VOD', 'VRNS', 'VRSK', 'VRSN', 'VRTA11.SA',
        'VRTX', 'VSLH11.SA', 'VSTE3.SA', 'VTEX', 'VTR', 'VULC3.SA', 'VVEO3.SA', 'VZ', 'W', 'WAB', 'WAL', 'WAT', 'WB', 'WBD', 'WDAY', 'WDC', 'WEB311.SA',
        'WEC', 'WEGE3.SA', 'WELL', 'WEST3.SA', 'WEX', 'WFC', 'WHGR11.SA', 'WHR', 'WHRL3.SA', 'WHRL4.SA', 'WIZC3.SA', 'WLY', 'WM', 'WMB', 'WMT', 'WPP',
        'WRB', 'WRLD11.SA', 'WSO', 'WST', 'WU', 'WY', 'WYNN', 'XEL', 'XFIX11.SA', 'XINA11.SA', 'XOM', 'XP', 'XPCA11.SA', 'XPCI11.SA', 'XPCM11.SA',
        'XPEV', 'XPID11.SA', 'XPIE11.SA', 'XPIN11.SA', 'XPLG11.SA', 'XPML11.SA', 'XRAY', 'XRPH11.SA', 'XRX', 'XYL', 'YDUQ3.SA', 'YUM', 'ZAVI11.SA',
        'ZBH', 'ZBRA', 'ZG', 'ZM', 'ZS', 'ZTO', 'ZTS',
    ],
    "MACRO_TICKERS": [
        "^VIX",
        "DX-Y.NYB",
        "GC=F",
        "BZ=F",
    ],
    "TABLE_TOP_N": 10,
    "CHART_TOP_N": 10,
    "INTERVAL": "1d",
    "PERIOD": "6mo",
    "HORIZONS": [1, 2, 3, 4, 5],
    "MIN_HISTORY_DAYS": 30,
    "RSI_PERIOD": 14,
    "MA_VOL_PERIOD": 20,
    "LAG_DAYS": [1, 3, 5, 10],
    "N_TRIALS": 45,
    "VAL_SIZE": 0.2,
    "PARQUET_FILE": "market_data.parquet",
}

FEATURE_COLS = (
    ["Ticker", "Log_Ret_Z", "RSI", "Rel_Volume", "OBV", "ATR"]
    + [f"Lag_{l}" for l in CONFIG["LAG_DAYS"]]
    + CONFIG["MACRO_TICKERS"]
)

# ==========================================
# SESSION 1: INGESTION & FILTERING
# ==========================================
def ingest_market_data(tickers: list, macro_tickers: list) -> pd.DataFrame:
    if os.path.exists(CONFIG["PARQUET_FILE"]):
        os.remove(CONFIG["PARQUET_FILE"])

    all_tickers = list(set(tickers + macro_tickers))
    raw_df = yf.download(
        all_tickers,
        period=CONFIG["PERIOD"],
        interval=CONFIG["INTERVAL"],
        auto_adjust=True,
        threads=True,
        progress=False,
    )

    macro_present = [c for c in macro_tickers if c in raw_df["Close"].columns]
    macro_df = raw_df["Close"][macro_present].copy()
    macro_df = macro_df.ffill().reset_index()

    main_present = [c for c in tickers if c in raw_df["Close"].columns]
    main_raw = raw_df.loc[:, (slice(None), main_present)]
    df = main_raw.stack(level=1, future_stack=True).reset_index()
    df.rename(columns={"level_1": "Ticker"}, inplace=True)
    df = df[
        ["Date", "Ticker", "Open", "High", "Low", "Close", "Volume"]
    ].dropna(subset=["Close"])

    counts = df["Ticker"].value_counts()
    valid_tickers = counts[counts >= CONFIG["MIN_HISTORY_DAYS"]].index
    df = df[df["Ticker"].isin(valid_tickers)]

    df.sort_values(by=["Ticker", "Date"], inplace=True)

    df = pd.merge(df, macro_df, on="Date", how="left")
    df[macro_present] = df.groupby("Ticker")[macro_present].ffill().bfill()

    df.to_parquet(CONFIG["PARQUET_FILE"])
    return df

# ==========================================
# SESSION 2: FEATURE ENGINEERING
# ==========================================
@numba.jit(nopython=True, nogil=True)
def compute_mid_price(
    high: np.ndarray, low: np.ndarray, close: np.ndarray
) -> np.ndarray:
    return (high + low + 2.0 * close) / 4.0

def calculate_technical_indicators(group: pd.DataFrame) -> pd.DataFrame:
    res = group.copy()
    high = res["High"].values
    low = res["Low"].values
    close = res["Close"].values
    volume = res["Volume"].values
    mid_price = res["Mid_Price"].values

    res["Log_Ret"] = np.insert(
        np.log(mid_price[1:] / mid_price[:-1]), 0, np.nan
    )
    res["RSI"] = talib.RSI(close, timeperiod=CONFIG["RSI_PERIOD"])

    ma_vol = talib.SMA(volume, timeperiod=CONFIG["MA_VOL_PERIOD"])
    res["Rel_Volume"] = np.where(ma_vol == 0, 0, volume / ma_vol)

    res["OBV"] = talib.OBV(close, volume)
    res["ATR"] = talib.ATR(high, low, close, timeperiod=CONFIG["RSI_PERIOD"])

    for lag in CONFIG["LAG_DAYS"]:
        res[f"Lag_{lag}"] = res["Log_Ret"].shift(lag)
    return res

def apply_feature_engineering(df: pd.DataFrame) -> pd.DataFrame:
    df["Mid_Price"] = compute_mid_price(
        df["High"].values.astype(np.float32),
        df["Low"].values.astype(np.float32),
        df["Close"].values.astype(np.float32),
    )

    df = df.groupby("Ticker", group_keys=False).apply(
        calculate_technical_indicators
    )

    rolling_window = CONFIG["MIN_HISTORY_DAYS"]
    df["Log_Ret_Z"] = df.groupby("Ticker")["Log_Ret"].transform(
        lambda x: (x - x.rolling(rolling_window, min_periods=1).mean())
        / x.rolling(rolling_window, min_periods=1).std()
    )

    return df

# ==========================================
# SESSION 3: TARGET ENGINEERING
# ==========================================
def create_ticker_targets(group: pd.DataFrame) -> pd.DataFrame:
    res = group.copy()
    for h in CONFIG["HORIZONS"]:
        future_price = res["Mid_Price"].shift(-h)
        raw_log_ret = np.log(future_price / res["Mid_Price"])
        res[f"Target_D{h}"] = np.clip(raw_log_ret, -0.40, 0.40)
    return res

def build_targets(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.groupby("Ticker", group_keys=False)
        .apply(create_ticker_targets)
        .reset_index(drop=True)
    )

# ==========================================
# SESSION 4: WALK-FORWARD & TUNING
# ==========================================
def walk_forward_split(df: pd.DataFrame, target_col: str):
    valid_features = [f for f in FEATURE_COLS if f in df.columns]
    valid_df = df.dropna(subset=[target_col] + valid_features).sort_values(
        by="Date"
    )

    split_idx = int(len(valid_df) * (1 - CONFIG["VAL_SIZE"]))

    X_train, y_train = (
        valid_df[valid_features].iloc[:split_idx],
        valid_df[target_col].iloc[:split_idx],
    )
    X_val, y_val = (
        valid_df[valid_features].iloc[split_idx:],
        valid_df[target_col].iloc[split_idx:],
    )

    return Pool(X_train, y_train, cat_features=["Ticker"]), Pool(
        X_val, y_val, cat_features=["Ticker"]
    )

class ObjectiveEvaluator:
    def __init__(self, train_pool, val_pool):
        self.tp, self.vp = train_pool, val_pool

    def __call__(self, trial):
        params = {
            "iterations": 500,
            "depth": trial.suggest_int("depth", 4, 8),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
            "loss_function": "MAE",
            "eval_metric": "MAE",
            "thread_count": -1,
            "border_count": 128,
            "max_ctr_complexity": 1,
            "verbose": 0,
            "task_type": "CPU",
        }
        model = CatBoostRegressor(**params)
        model.fit(self.tp, eval_set=self.vp)
        return model.get_best_score()["validation"]["MAE"]

def tune_and_train(tp, vp):
    study = optuna.create_study(
        direction="minimize",
        pruner=optuna.pruners.MedianPruner(n_warmup_steps=10)
    )
    study.optimize(ObjectiveEvaluator(tp, vp), n_trials=CONFIG["N_TRIALS"])

    best_params = study.best_params
    best_params.update({
        "iterations": 1000,
        "loss_function": "MAE",
        "eval_metric": "MAE",
        "thread_count": -1,
        "border_count": 128,
        "max_ctr_complexity": 1,
        "verbose": 0,
        "task_type": "CPU",
    })

    model = CatBoostRegressor(**best_params)
    model.fit(tp, eval_set=vp)
    return model

# ==========================================
# SESSION 6: REPORTING & VISUALIZATION
# ==========================================
def generate_prd_outputs(df_model, models):
    valid_features = [f for f in FEATURE_COLS if f in df_model.columns]
    latest_data = (
        df_model.dropna(subset=valid_features).groupby("Ticker").tail(1).copy()
    )
    results = []

    max_h = max(CONFIG["HORIZONS"])
    target_max = f"Target_D{max_h}"
    mae_global = (
        models[target_max].get_best_score()["validation"]["MAE"] * 100
    )

    for _, row in latest_data.iterrows():
        ticker = row["Ticker"]
        curr = row["Close"]

        ticker_res = {"Ticker": ticker, "Preço Atual": curr}

        for h in CONFIG["HORIZONS"]:
            target = f"Target_D{h}"
            pred_log = models[target].predict(row[valid_features])
            pred_log = np.clip(pred_log, -0.40, 0.40)
            ticker_res[f"D+{h}"] = np.exp(pred_log) * curr

        p_max = ticker_res[f"D+{max_h}"]
        var_max = ((p_max / curr) - 1) * 100

        ticker_res[f"Var % (D+{max_h})"] = var_max
        ticker_res["Direção"] = "ALTA" if var_max > 0 else "BAIXA"
        results.append(ticker_res)

    sort_col = f"Var % (D+{max_h})"
    report_df = pd.DataFrame(results).sort_values(by=sort_col, ascending=False)

    display(HTML(f"<h3>Tabela de Projeções (Top {CONFIG['TABLE_TOP_N']}) | Erro Médio Global (MAE D+{max_h}): {mae_global:.1f}%</h3>"))

    fmt = {
        "Preço Atual": "{:.2f}",
        sort_col: "{:+.1f}%",
    }
    for h in CONFIG["HORIZONS"]:
        fmt[f"Proj. D+{h}"] = "{:.2f}"

    table_df = report_df.head(CONFIG["TABLE_TOP_N"])
    styled_table = table_df.style.format(fmt).hide(axis="index")
    display(styled_table)

    n_charts = CONFIG["CHART_TOP_N"]
    if n_charts <= 0:
        print("\n[i] Geração de gráficos desativada (CHART_TOP_N = 0).")
        return

    tickers_to_plot = report_df.head(n_charts)["Ticker"].unique()
    n_rows = max(1, (len(tickers_to_plot) + 1) // 2)

    display(HTML(f"<h3>Trajetórias Preditivas (Top {len(tickers_to_plot)})</h3>"))
    fig, axes = plt.subplots(n_rows, 2, figsize=(15, 5 * n_rows))

    if hasattr(axes, "flatten"):
        axes = axes.flatten()
    else:
        axes = [axes]

    for i, ticker in enumerate(tickers_to_plot):
        ax = axes[i]
        hist = df_model[df_model["Ticker"] == ticker].tail(30)
        ax.plot(
            hist["Date"],
            hist["Close"],
            color="#2c3e50",
            lw=2,
            label="Histórico",
        )

        t_now = hist["Date"].iloc[-1]
        ax.axvline(x=t_now, color="red", ls="--", alpha=0.5)

        res_t = report_df[report_df["Ticker"] == ticker].iloc[0]
        future_dates = [
            t_now + pd.Timedelta(days=d) for d in CONFIG["HORIZONS"]
        ]
        projs = [res_t[f"Proj. D+{d}"] for d in CONFIG["HORIZONS"]]

        ax.plot(future_dates, projs, "o--", color="#27ae60", label="Predição")
        ax.fill_between(
            future_dates,
            [p * (1 - mae_global / 100) for p in projs],
            [p * (1 + mae_global / 100) for p in projs],
            color="#27ae60",
            alpha=0.1,
        )

        ax.set_title(f"Trajectory: {ticker}", fontweight="bold")
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)
        ax.tick_params(axis="x", rotation=30)

    for j in range(len(tickers_to_plot), len(axes)):
        fig.delaxes(axes[j])

    plt.tight_layout()
    plt.show()

def main():
    print("1. Ingesting Data...")
    df = ingest_market_data(CONFIG["TICKERS"], CONFIG["MACRO_TICKERS"])

    print("2. Engineering Features...")
    df = apply_feature_engineering(df)

    print("3. Building Targets...")
    df = build_targets(df)

    models = {}
    for h in CONFIG["HORIZONS"]:
        target = f"Target_D{h}"
        print(f"4. Processing {target}...")
        tp, vp = walk_forward_split(df, target)
        models[target] = tune_and_train(tp, vp)

    generate_prd_outputs(df, models)

if __name__ == "__main__":
    main()